CREATE TABLE USER_SUGGESTED_REPLENISHMENT (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    LocationID VARCHAR(10),
    ItemID VARCHAR(20),
    SuggestedQuantity DECIMAL(18, 2),
    DateCreated DATETIME
);
